name       : haskell-primitive
version    : 0.6.3.0
release    : 5
source     :
    - https://hackage.haskell.org/package/primitive-0.6.3.0/primitive-0.6.3.0.tar.gz : cddeff804e0f577f1be0179d5d145dfc170f8bfb66f663b9fba67104a45d9555
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides various primitive memory-related operations.
description: |
    This package provides various primitive memory-related operations.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/primitive-*/include
