name       : haskell-primitive
version    : 0.6.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/primitive-0.6.1.0/primitive-0.6.1.0.tar.gz : 93731fa72eaf74e8e83453f080828e18cec9fbc82bee91b49ba8b61c043d38c8
license    : BSD-3-Clause
component  : programming
summary    : This package provides various primitive memory-related operations.
description: |
    This package provides various primitive memory-related operations.
builddeps  :
    - ghc
setup      : |
    sed -i "s|4.9|4.10|g" primitive.cabal
    sed -i "s|0.5|0.6|g" primitive.cabal
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 primitive-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/primitive-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/primitive-$version/*.a
