name       : haskell-primitive
version    : 0.6.1.0
release    : 3
source     :
    - http://hackage.haskell.org/package/primitive-0.6.1.0/primitive-0.6.1.0.tar.gz : 93731fa72eaf74e8e83453f080828e18cec9fbc82bee91b49ba8b61c043d38c8
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides various primitive memory-related operations.
description: |
    This package provides various primitive memory-related operations.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    sed -i "s|4.9|4.10|g" primitive.cabal
    sed -i "s|0.5|0.6|g" primitive.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
patterns   :
    - devel :
        - /usr/lib64/ghc-*/primitive-*/include
